{% set name = "treevalue" %}
{% set version = "1.4.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/treevalue-{{ version }}.tar.gz
  sha256: cccedeb4a7453edd3a207d8d3c0a20411d873ef45feef5576d22218410e8d3f1

build:
  skip: true  # [py<37]
  entry_points:
    - treevalue=treevalue.entry.cli:treevalue_cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools >=42
    - wheel
    - cython >=0.29  # [not win]
    - pip
  run:
    - python
    - enum_tools
    - python-graphviz >=0.17
    - dill >=0.3.4
    - click >=7.1.0
    - hbutils >=0.9.1

test:
  imports:
    - treevalue
  commands:
    - pip check
    - treevalue --help
  requires:
    - pip

about:
  home: https://github.com/HansBug/treevalue
  summary: A flexible, generalized tree-based data structure.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - huangshiyu
