{% set name = "openrl" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openrl-{{ version }}.tar.gz
  sha256: 6b1f9098a8c8e5d8781deb7115db509b1072a33012c7d9ad2b24a32ceae62950

build:
  entry_points:
    - openrl=openrl.cli.cli:run
  noarch: python
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python >=3.8
    - pip
    - cython
  run:
    - python >=3.8
    - setuptools >=67.0
    - gymnasium
    - click
    - termcolor
    - gym
    - pytorch
    - rich
    - wandb
    - seaborn
    - jsonargparse
    - imageio
    - opencv
    - pygame
    - mujoco
    - tqdm
    - jinja2


test:
  imports:
    - openrl
  commands:
    - pip check
    - openrl --help
  requires:
    - pip

about:
  home: https://github.com/OpenRL-Lab/openrl
  summary: unified reinforcement learning framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - huangshiyu
