{% set name = "hbutils" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hbutils-{{ version }}.tar.gz
  sha256: f153ee3afe30446bab74fd2d2a60238900ad6ad4e060f6e00e6d64fd26251029

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - packaging >=21.3
    - setuptools >=50.0
    - pytimeparse >=1.1.8
    - bitmath >=1.3.3.1
    - chardet <5,>=3.0.4
    - deprecation >=2.0.0
    - importlib-metadata >=6.0.0  # [py<38]

test:
  imports:
    - hbutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hansbug/hbutils
  summary: Some useful functions and classes in Python infrastructure development.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - huangshiyu
